version: "3.9"

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bjubot
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
